In [7]:
import numpy as np
import pygame
import math
import sys


SQUARE_COUNT = 7
SQUARE_SIZE = 75
BLUE = (0,0,255)
RED = (255,0,0)
GREY = (182,179,179)
WHITE = (255,255,255)
BLACK = (0,0,0)
width = SQUARE_COUNT * SQUARE_SIZE
height = SQUARE_COUNT * SQUARE_SIZE
size = (width, height)







def create_board():
    board = np.zeros((SQUARE_COUNT,SQUARE_COUNT))
    board[0][0] = 1
    board[6][6] = 1
    board[0][6] = 2
    board[6][0] = 2
    return board
        

def is_valid_location(board, x, y):
    return board[x][y] == 0


def place(board, x, y, piece):
    board[x][y] = piece 

        
def jump(board, c, r, x, y, piece):
    board[r][c] = 0
    board[x][y] = piece
               
                
def change(board, r, c):
    for i in range(SQUARE_COUNT):
        for l in range(SQUARE_COUNT):
            if i == r + 2:
                if (l == c - 2 or l == c - 1 or l == c or l == c + 1 or l == c + 2) and board[i][l] == 0:
                    board[i][l] = 4            
            if i == r + 1:
                if (l == c - 1 or l == c or l == c + 1) and board[i][l] == 0:
                    board[i][l] = 3
                if (l == c - 2 or l == c + 2) and board[i][l] == 0:
                    board[i][l] = 4
            if i == r:
                if (l == c - 1 or l == c + 1) and board[i][l] == 0:
                    board[i][l] = 3
                if (l == c - 2 or l == c + 2) and board[i][l] == 0:
                    board[i][l] = 4
            if i == r - 1:
                if (l == c - 1 or l == c or l == c + 1) and board[i][l] == 0:
                    board[i][l] = 3
                if (l == c - 2 or l == c + 2) and board[i][l] == 0:
                    board[i][l] = 4
            if i == r - 2:
                if (l == c - 2 or l == c - 1 or l == c or l == c + 1 or l == c + 2) and board[i][l] == 0:
                    board[i][l] = 4        
            
                
def change_back(board):
    for i in range(SQUARE_COUNT):
        for l in range(SQUARE_COUNT):
            if board[i][l] == 3 or board[i][l] == 4:
                board[i][l] = 0        
        

def eat(board, x, y, not_piece):
    if x-1 >= 0 and x-1 <= 6 and y-1 >= 0 and y-1 <=6 and board[x-1][y-1] == not_piece: board[x-1][y-1] = piece
    if x-1 >= 0 and x-1 <= 6 and y >= 0 and y <=6 and board[x-1][y] == not_piece: board[x-1][y] = piece    
    if x-1 >= 0 and x-1 <= 6 and y+1 >= 0 and y+1 <=6 and board[x-1][y+1] == not_piece : board[x-1][y+1] = piece    
    if x >= 0 and x <= 6 and y-1 >= 0 and y-1 <=6 and board[x][y-1] == not_piece: board[x][y-1] = piece      
    if x >= 0 and x <= 6 and y+1 >= 0 and y+1 <=6 and board[x][y+1] == not_piece: board[x][y+1] = piece   
    if x+1 >= 0 and x+1 <= 6 and y-1 >= 0 and y-1 <=6 and board[x+1][y-1] == not_piece: board[x+1][y-1] = piece
    if x+1 >= 0 and x+1 <= 6 and y >= 0 and y <=6 and board[x+1][y] == not_piece: board[x+1][y] = piece    
    if x+1 >= 0 and x+1 <= 6 and y+1 >= 0 and y+1 <=6 and board[x+1][y+1] == not_piece: board[x+1][y+1] = piece    
        

def not_piece_counter(board, not_piece):
    not_piece_count = 0
    for i in range(SQUARE_COUNT):
        for l in range(SQUARE_COUNT):
            if board[i][l] == not_piece:
                not_piece_count += 1
    if not_piece_counter:
        return True
        
def winning_move(board, not_piece):
    available_moves = 0
    for i in range(SQUARE_COUNT):
        for l in range(SQUARE_COUNT):
            if board[i][l] == not_piece:
                for m in range(-1, 2):
                    for n in range(-1, 2):
                        if i+m <= 6 and i+m >=0 and l+n <= 6 and l+n >=0: 
                            if board[i+m][l+n] == 0:
                                available_moves += 1
    if available_moves == 0 or not not_piece_counter:
        return True

        
def draw_pieces(board):
    
    for k in range(SQUARE_COUNT):
        for l in range(SQUARE_COUNT):
            pygame.draw.circle(screen, BLACK, (int((l+1)*SQUARE_SIZE - SQUARE_SIZE/2),int((k+1)*SQUARE_SIZE - SQUARE_SIZE/2)), SQUARE_SIZE/3)
            if board[k][l] == 1:
                pygame.draw.circle(screen, RED, (int((l+1)*SQUARE_SIZE - SQUARE_SIZE/2),int((k+1)*SQUARE_SIZE - SQUARE_SIZE/2)), SQUARE_SIZE/3)
            if board[k][l] == 2:
                pygame.draw.circle(screen, BLUE, (int((l+1)*SQUARE_SIZE - SQUARE_SIZE/2),int((k+1)*SQUARE_SIZE - SQUARE_SIZE/2)), SQUARE_SIZE/3)
            if board[k][l] == 3 or board[k][l] == 4:
                pygame.draw.circle(screen, GREY, (int((l+1)*SQUARE_SIZE - SQUARE_SIZE/2),int((k+1)*SQUARE_SIZE - SQUARE_SIZE/2)), SQUARE_SIZE/3)   
    pygame.display.update()
     
        
def draw_lines(board):
    for i in range(SQUARE_COUNT -  1):
        pygame.draw.line(screen, WHITE, ((i+1)*SQUARE_SIZE,0), ((i+1)*SQUARE_SIZE,SQUARE_SIZE*SQUARE_COUNT)) 
        pygame.draw.line(screen, WHITE, (0,(i+1)*SQUARE_SIZE), (SQUARE_SIZE*SQUARE_COUNT,(i+1)*SQUARE_SIZE))    
    pygame.display.update()   
        
        
        
        
        
        

        
        
        
        
        
        
        
        
        
        
        
        
        
        
screen = pygame.display.set_mode(size)
board = create_board()
print(board)

game_over = False
turn = 0                
        
        
pygame.init()        
screen = pygame.display.set_mode(size)   
board = create_board() 
draw_lines(board)
draw_pieces(board)
pygame.display.update() 
font_size = 50
myfont = pygame.font.Font(None, font_size)        
clicks = 0        
        
        

while not game_over:
    
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()

        if event.type == pygame.MOUSEBUTTONDOWN:  
            #ASK FOR PLAYER 1 INPUT
            if turn == 0:
                piece = 1
                not_piece = 2
                if clicks == 0:
                    posc = event.pos[0]
                    c = int(math.floor(posc/SQUARE_SIZE))
                    posr = event.pos[1]
                    r = int(math.floor(posr/SQUARE_SIZE))
                    if board[r][c] == piece:
                        change(board, r, c)
                        print(board)
                        draw_pieces(board)
                        pygame.display.update()
                        clicks = 1
                if clicks == 1:
                    posy = event.pos[0]
                    y = int(math.floor(posy/SQUARE_SIZE))
                    posx = event.pos[1]
                    x = int(math.floor(posx/SQUARE_SIZE))
                    if board[x][y] == 3:
                        place(board, x, y, piece)
                        eat(board, x, y, not_piece)
                        turn += 1
                        turn = turn % 2
                        change_back(board)
                        print(board)
                        draw_pieces(board)
                        pygame.display.update()
                        clicks = 0
                        if winning_move(board, not_piece):
                            label = myfont.render("PLAYER 1 WINS!!!", True, WHITE, BLACK)
                            screen.blit(label, (110,SQUARE_SIZE*SQUARE_COUNT/2 - 10))
                            pygame.display.update()
                            print("PLAYER 1 WINS!!!")
                            game_over = True
                    elif board[x][y] == 4:
                        jump(board, c, r, x, y, piece)
                        eat(board, x, y, not_piece)
                        turn += 1
                        turn = turn % 2
                        change_back(board)
                        print(board)
                        draw_pieces(board)
                        pygame.display.update()
                        clicks = 0
                        if winning_move(board, not_piece):
                            label = myfont.render("PLAYER 1 WINS!!!", True, WHITE, BLACK)
                            screen.blit(label, (110,SQUARE_SIZE*SQUARE_COUNT/2 - 10))
                            pygame.display.update()
                            print("PLAYER 1 WINS!!!")
                            game_over = True
                    else:
                        if board[x][y] == piece:
                            change_back(board)
                            r = x
                            c = y
                            change(board, r, c)
                            draw_pieces(board)
                            pygame.display.update()
                        else:
                            change_back(board)
                            draw_pieces(board)
                            pygame.display.update()
                    
                    
                    
                    
                    
                    
                    


            #ASK FOR PLAYER 2 INPUT
            if turn != 0:
                piece = 2
                not_piece = 1
                if clicks == 0:
                    posc = event.pos[0]
                    c = int(math.floor(posc/SQUARE_SIZE))
                    posr = event.pos[1]
                    r = int(math.floor(posr/SQUARE_SIZE))
                    if board[r][c] == piece:
                        change(board, r, c)
                        print(board)
                        draw_pieces(board)
                        pygame.display.update()
                        clicks = 1
                if clicks == 1:
                    posy = event.pos[0]
                    y = int(math.floor(posy/SQUARE_SIZE))
                    posx = event.pos[1]
                    x = int(math.floor(posx/SQUARE_SIZE))
                    if board[x][y] == 3:
                        place(board, x, y, piece)
                        eat(board, x, y, not_piece)
                        turn += 1
                        turn = turn % 2
                        change_back(board)
                        print(board)
                        draw_pieces(board)
                        pygame.display.update()
                        clicks = 0
                        if winning_move(board, not_piece):
                            label = myfont.render("PLAYER 2 WINS!!!", True, WHITE, BLACK)
                            screen.blit(label, (110,SQUARE_SIZE*SQUARE_COUNT/2 - 10))
                            pygame.display.update()
                            print("PLAYER 2 WINS!!!")
                            game_over = True
                    elif board[x][y] == 4:
                        jump(board, c, r, x, y, piece)
                        eat(board, x, y, not_piece)
                        turn += 1
                        turn = turn % 2
                        change_back(board)
                        print(board)
                        draw_pieces(board)
                        pygame.display.update()
                        clicks = 0
                        if winning_move(board, not_piece):
                            label = myfont.render("PLAYER 2 WINS!!!", True, WHITE, BLACK)
                            screen.blit(label, (110,SQUARE_SIZE*SQUARE_COUNT/2 - 10))
                            pygame.display.update()
                            print("PLAYER 2 WINS!!!")
                            game_over = True
                    else:
                        if board[x][y] == piece:
                            change_back(board)
                            r = x
                            c = y
                            change(board, r, c)
                            draw_pieces(board)
                            pygame.display.update()
                        else:
                            change_back(board)
                            draw_pieces(board)
                            pygame.display.update()




            if game_over:
                pygame.time.wait(3000)
                pygame.quit()
                sys.exit()

        
        
        
        
        
        
        
        

[[1. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 1.]]
[[1. 3. 4. 0. 0. 0. 2.]
 [3. 3. 4. 0. 0. 0. 0.]
 [4. 4. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [4. 4. 4. 0. 1. 0. 0.]
 [3. 3. 4. 0. 0. 0. 0.]
 [2. 3. 4. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 4. 4. 4. 4. 4.]
 [0. 0. 4. 3. 3. 3. 4.]
 [0. 0. 2. 3. 1. 3. 4.]
 [0. 0. 4. 3. 3. 3. 4.]
 [0. 0. 4. 

SystemExit: 